/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OchranaSukromiaRouteImport } from './routes/ochrana-sukromia'
import { Route as PodakovanieRouteImport } from './routes/podakovanie'
import { Route as SluzbyRouteImport } from './routes/sluzby'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaSukromiaRoute = OchranaSukromiaRouteImport.update({
  id: '/ochrana-sukromia',
  path: '/ochrana-sukromia',
  getParentRoute: () => rootRouteImport,
} as any)
const PodakovanieRoute = PodakovanieRouteImport.update({
  id: '/podakovanie',
  path: '/podakovanie',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/ochrana-sukromia': typeof OchranaSukromiaRoute
  '/podakovanie': typeof PodakovanieRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/ochrana-sukromia': typeof OchranaSukromiaRoute
  '/podakovanie': typeof PodakovanieRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/kontakt': typeof KontaktRoute
  '/ochrana-sukromia': typeof OchranaSukromiaRoute
  '/podakovanie': typeof PodakovanieRoute
  '/sluzby': typeof SluzbyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/kontakt'
    | '/ochrana-sukromia'
    | '/podakovanie'
    | '/sluzby'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/kontakt'
    | '/ochrana-sukromia'
    | '/podakovanie'
    | '/sluzby'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/kontakt'
    | '/ochrana-sukromia'
    | '/podakovanie'
    | '/sluzby'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  KontaktRoute: typeof KontaktRoute
  OchranaSukromiaRoute: typeof OchranaSukromiaRoute
  PodakovanieRoute: typeof PodakovanieRoute
  SluzbyRoute: typeof SluzbyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-sukromia': {
      id: '/ochrana-sukromia'
      path: '/ochrana-sukromia'
      fullPath: '/ochrana-sukromia'
      preLoaderRoute: typeof OchranaSukromiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podakovanie': {
      id: '/podakovanie'
      path: '/podakovanie'
      fullPath: '/podakovanie'
      preLoaderRoute: typeof PodakovanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  KontaktRoute: KontaktRoute,
  OchranaSukromiaRoute: OchranaSukromiaRoute,
  PodakovanieRoute: PodakovanieRoute,
  SluzbyRoute: SluzbyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
